---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.roleName }}
rules:
- apiGroups:
  - jabbs19.com
  resources:
  - resourcewatchers
  - resourcewatchers/finalizers
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
# - apiGroups:
#   - "*"
#   resources:
#   - "*"
#   verbs:
#   - get
#   - list
#   - watch
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccountName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
---
