apiVersion: jabbs19.com/v1
kind: ResourceWatcher
metadata:
  name: resource-watcher-service
  finalizers: ["must.delete.manually.for.now"]
spec:
  deployNamespace: resource-watcher-testnamespace
  watchNamespace: resource-watcher-testnamespace
  k8sApiVersion: CoreV1Api
  k8sApiResourceName: list_namespaced_service
  k8sAPIkwArgs: '{"namespace":"resource-watcher-testnamespace"}'
  annotationFilterKey: 'service-watcher-key'
  annotationFilterValue: annotationTriggerString
  eventTypeFilter: ["ADDED","UPDATED","DELETED"]
  eventTypeFilterString: '["ADDED","UPDATED","DELETED"]'
  eventAction: 'CUSTOM'
  pathToCa: '/path/to/ca'
  jwtTokenValue: '86753099999999'
